spring.application.name=shopwise-api

spring.datasource.url=jdbc:postgresql://localhost:5434/shopwise
spring.datasource.username=shopwise
spring.datasource.password=shopwise

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
