-- ShopWise - structure PostgreSQL 17
-- Ce script est execute avant 02-seed.sql par l'image officielle PostgreSQL.

CREATE TABLE IF NOT EXISTS businesses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS merchant_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS business_memberships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_account_id BIGINT NOT NULL REFERENCES merchant_accounts(id),
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    role VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uk_membership_account_business UNIQUE (merchant_account_id, business_id),
    CONSTRAINT ck_business_membership_role CHECK (role IN ('OWNER', 'MANAGER', 'STAFF'))
);

CREATE TABLE IF NOT EXISTS merchant_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    email VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'PENDING',
    created_by_id BIGINT NOT NULL REFERENCES merchant_accounts(id),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    accepted_at TIMESTAMP,
    CONSTRAINT ck_merchant_invitation_role CHECK (role IN ('OWNER', 'MANAGER', 'STAFF')),
    CONSTRAINT ck_merchant_invitation_status CHECK (status IN ('PENDING', 'ACCEPTED', 'REVOKED', 'EXPIRED'))
);

CREATE TABLE IF NOT EXISTS clients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS customer_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    password_hash VARCHAR(255) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    last_login TIMESTAMP
);

CREATE TABLE IF NOT EXISTS services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    duration_minutes INTEGER NOT NULL,
    loyalty_points INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_service_duration CHECK (duration_minutes > 0),
    CONSTRAINT ck_service_loyalty_points CHECK (loyalty_points >= 0)
);

CREATE TABLE IF NOT EXISTS appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL REFERENCES businesses(id),
    client_id BIGINT NOT NULL REFERENCES clients(id),
    service_id BIGINT NOT NULL REFERENCES services(id),
    created_by_account_id BIGINT REFERENCES merchant_accounts(id),
    starts_at TIMESTAMP NOT NULL,
    ends_at TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'SCHEDULED',
    comment VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_appointment_dates CHECK (ends_at > starts_at),
    CONSTRAINT ck_appointment_status CHECK (status IN ('SCHEDULED', 'HONORED', 'CANCELED'))
);

CREATE TABLE IF NOT EXISTS loyalty_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL UNIQUE REFERENCES clients(id),
    points_balance INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_loyalty_balance CHECK (points_balance >= 0)
);

CREATE TABLE IF NOT EXISTS loyalty_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loyalty_account_id BIGINT NOT NULL REFERENCES loyalty_accounts(id),
    appointment_id BIGINT UNIQUE REFERENCES appointments(id),
    type VARCHAR(255) NOT NULL,
    points_delta INTEGER NOT NULL,
    reason VARCHAR(255) NOT NULL,
    transaction_date TIMESTAMP NOT NULL,
    CONSTRAINT ck_loyalty_transaction_type CHECK (type IN ('EARNED', 'REDEEMED', 'ADJUSTMENT'))
);

CREATE INDEX IF NOT EXISTS idx_memberships_business ON business_memberships(business_id);
CREATE INDEX IF NOT EXISTS idx_invitations_business ON merchant_invitations(business_id);
CREATE INDEX IF NOT EXISTS idx_clients_business ON clients(business_id);
CREATE INDEX IF NOT EXISTS idx_services_business ON services(business_id);
CREATE INDEX IF NOT EXISTS idx_appointments_business_start ON appointments(business_id, starts_at);
CREATE INDEX IF NOT EXISTS idx_appointments_client ON appointments(client_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_transactions_account_date
    ON loyalty_transactions(loyalty_account_id, transaction_date DESC);
